### ISSUE TITLE
Separate out "appendix" material?

### ISSUE THREAD

**Issue by gwd** [bluekeyes/go-gitdiff#18]
Similar to #16: `git format-patch` often adds stuff after a `---` line; and many people add things there too.  So you might have a message that looks like this:

```
Subject: [PATCH] Implement foo bar

Blah blah blah

S-o-b: <n@b.com>
---
CC: person1@company.com
CC: person2@company.com

 xen/common/domain.c | 10 ++++++++++
 1 file changed, 10 insertions(+)
```

`git am` always ends up removing anything after the `---`, because it actually interprets `---` as the beginning of the patch.

Would you be open to having `PatchPatchHeader` separate out this extra information into a separate field?  Maybe, `BodyAppendix` or something like that?

If so I can write something up & send a PR.

**Comment by bluekeyes** [comment]
This sounds reasonable to me: for email formatted preambles, split the body at the first `---` and store everything after in `BodySuffix`.
