### ISSUE TITLE
isSourceLine ignore line "--------------------------------------"

### ISSUE THREAD

**Issue by nemax** [bluekeyes/go-gitdiff#39]
![image](https://user-images.githubusercontent.com/1342652/224697282-16db18d2-58ea-45a7-927a-c93b570766cf.png)

since the source contains a line as "--------------------------------------" the isSourceLine function just ignore it, i wonder if the condition should be changed as below

if l := len(line); l == 0 || (l >= 3 && (line[:4] == "--- " || line[:4] == "+++ ")) {

**Comment by bluekeyes** [comment]
Thanks for reporting this. Do you have a patch you can share that fails for this reason? I'd like to see how the `---------` line appears in context before implementing a fix.

**Comment by nemax** [comment]
![image](https://user-images.githubusercontent.com/1342652/224879030-fc06971f-4dcb-442c-a8a1-1348bf4dac9e.png)
sorry, because of company policy, i could only show you a small scope , the "-------------------------------------" line just show up to make segments in comment

**Comment by bluekeyes** [comment]
After looking at this more, I think you might have the wrong library - this package does not contain the `isSourceLine` function. A GitHub search found https://github.com/waigani/diffparser (and a few forks), which looks like a match.

For what it's worth, this library correctly parses these types of patches:

```go
package main

import (
        "bytes"
        "fmt"

        "github.com/bluekeyes/go-gitdiff/gitdiff"
)

var content = []byte(`
--- main.c      2023-03-13 20:34:05.176688747 -0700
+++ main.c      2023-03-13 20:33:01.656701997 -0700
@@ -1,17 +1,3 @@
-/*
-
-This file contains parsing code for JSON.
-
-----------------------------------------
-{"key": "value"}
-{"key": "value"}
-{"key": "value"}
-----------------------------------------
-
-Here's some other content.
-
-*/
-
 int main(int argc, char *argv[])
 {
 }
`)

func main() {
        files, _, err := gitdiff.Parse(bytes.NewReader(content))
        if err != nil {
                panic(err)
        }

        for _, frag := range files[0].TextFragments {
                fmt.Printf("text fragment with +%d/-%d lines\n", frag.LinesAdded, frag.LinesDeleted)
        }
}
```
```
$ go run main.go
text fragment with +0/-14 lines
```

**Comment by nemax** [comment]
ah, so sorry, another member introduce [waigani/diffparser](https://github.com/waigani/diffparser) and i was confused with that while i`m debugging...LOL，thank u for your answer
