### ISSUE TITLE
Support empty patches

### ISSUE THREAD

**Issue by neurosnap** [bluekeyes/go-gitdiff#45]
Hi!

We are using this lib over at https://pr.pico.sh and so far haven't had any issues.  So thank you for your hard work!

We are trying to support cover letters in our patch request workflow, but it looks like since the patch itself is empty, `go-gitdiff` skips over it and returns empty header data.  Ideally this lib would still process the empty patch even if there aren't any diffs in it.

I'm curious what you think about adding support for empty patches?

**Comment by bluekeyes** [comment]
This sounds like something that would be reasonable to support, but I'm a little unclear on exactly what an empty patch looks like in this case. Do you have an example patch I could look at to test the current behavior and verify any changes?

**Comment by neurosnap** [comment]
https://github.com/picosh/git-pr/blob/main/fixtures/with-cover.patch

**Comment by bluekeyes** [comment]
This should be fixed in the latest commit. Please try it out and if it works the way you expected, I'll tag a new release.

**Comment by neurosnap** [comment]
This worked for me, thanks so much!
